// Static data loading. Everything is read at build time from web/public/data (generated by
// scripts/export_web_data.py), so the demo never depends on a live server.

import fs from "node:fs";
import path from "node:path";
import type { Participant, ParticipantIndex, SkillStratum, LeaderboardRow } from "./types";

const DATA = path.join(process.cwd(), "public", "data");

function read<T>(rel: string): T {
  return JSON.parse(fs.readFileSync(path.join(DATA, rel), "utf-8")) as T;
}

export function participantIndex(): ParticipantIndex[] {
  return read<ParticipantIndex[]>("participants/index.json");
}

export function participant(pid: string): Participant {
  return read<Participant>(`participants/${pid}.json`);
}

export function skill(): { strata: SkillStratum[] } {
  return read("skill.json");
}

export function leaderboard(): LeaderboardRow[] {
  return read<LeaderboardRow[]>("leaderboard.json");
}
